name: Fastlane Release

on:
  push:
    branches: [ main ]
concurrency: 
  group: ${{ github.ref }}
  cancel-in-progress: true
jobs:
  build:
    name: Release MacOS app with Fastlane
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3
      
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
          bundler-cache: true

      - uses: maierj/fastlane-action@v3.0.0
        with:
          lane: 'release'